/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DemoReviewRouteImport } from './routes/demo-review'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as SSubmissionIdRouteImport } from './routes/s.$submissionId'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as ExploreSlugRouteImport } from './routes/explore.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedSubmissionSubmissionIdRouteImport } from './routes/_authenticated/submission.$submissionId'
import { Route as AuthenticatedSettingsExportRouteImport } from './routes/_authenticated/settings.export'
import { Route as AuthenticatedAdminUpdatePriceRouteImport } from './routes/_authenticated/admin.update-price'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSeatsRouteImport } from './routes/_authenticated/admin.seats'
import { Route as AuthenticatedAdminResearchRouteImport } from './routes/_authenticated/admin.research'
import { Route as AuthenticatedAdminExportRouteImport } from './routes/_authenticated/admin.export'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminCurriculumRouteImport } from './routes/_authenticated/admin.curriculum'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicOgSubmissionIdRouteImport } from './routes/api/public/og.$submissionId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoReviewRoute = DemoReviewRouteImport.update({
  id: '/demo-review',
  path: '/demo-review',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const SSubmissionIdRoute = SSubmissionIdRouteImport.update({
  id: '/s/$submissionId',
  path: '/s/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const ExploreSlugRoute = ExploreSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExploreRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmissionSubmissionIdRoute =
  AuthenticatedSubmissionSubmissionIdRouteImport.update({
    id: '/submission/$submissionId',
    path: '/submission/$submissionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsExportRoute =
  AuthenticatedSettingsExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedAdminUpdatePriceRoute =
  AuthenticatedAdminUpdatePriceRouteImport.update({
    id: '/admin/update-price',
    path: '/admin/update-price',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSeatsRoute = AuthenticatedAdminSeatsRouteImport.update({
  id: '/admin/seats',
  path: '/admin/seats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminResearchRoute =
  AuthenticatedAdminResearchRouteImport.update({
    id: '/admin/research',
    path: '/admin/research',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminExportRoute =
  AuthenticatedAdminExportRouteImport.update({
    id: '/admin/export',
    path: '/admin/export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCurriculumRoute =
  AuthenticatedAdminCurriculumRouteImport.update({
    id: '/admin/curriculum',
    path: '/admin/curriculum',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOgSubmissionIdRoute = ApiPublicOgSubmissionIdRouteImport.update({
  id: '/api/public/og/$submissionId',
  path: '/api/public/og/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/demo-review': typeof DemoReviewRoute
  '/explore': typeof ExploreRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/s/$submissionId': typeof SSubmissionIdRoute
  '/learn/': typeof LearnIndexRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/curriculum': typeof AuthenticatedAdminCurriculumRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/export': typeof AuthenticatedAdminExportRoute
  '/admin/research': typeof AuthenticatedAdminResearchRoute
  '/admin/seats': typeof AuthenticatedAdminSeatsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/update-price': typeof AuthenticatedAdminUpdatePriceRoute
  '/settings/export': typeof AuthenticatedSettingsExportRoute
  '/submission/$submissionId': typeof AuthenticatedSubmissionSubmissionIdRoute
  '/api/public/og/$submissionId': typeof ApiPublicOgSubmissionIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/demo-review': typeof DemoReviewRoute
  '/explore': typeof ExploreRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/s/$submissionId': typeof SSubmissionIdRoute
  '/learn': typeof LearnIndexRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/curriculum': typeof AuthenticatedAdminCurriculumRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/export': typeof AuthenticatedAdminExportRoute
  '/admin/research': typeof AuthenticatedAdminResearchRoute
  '/admin/seats': typeof AuthenticatedAdminSeatsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/update-price': typeof AuthenticatedAdminUpdatePriceRoute
  '/settings/export': typeof AuthenticatedSettingsExportRoute
  '/submission/$submissionId': typeof AuthenticatedSubmissionSubmissionIdRoute
  '/api/public/og/$submissionId': typeof ApiPublicOgSubmissionIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/demo-review': typeof DemoReviewRoute
  '/explore': typeof ExploreRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/s/$submissionId': typeof SSubmissionIdRoute
  '/learn/': typeof LearnIndexRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/curriculum': typeof AuthenticatedAdminCurriculumRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/export': typeof AuthenticatedAdminExportRoute
  '/_authenticated/admin/research': typeof AuthenticatedAdminResearchRoute
  '/_authenticated/admin/seats': typeof AuthenticatedAdminSeatsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/update-price': typeof AuthenticatedAdminUpdatePriceRoute
  '/_authenticated/settings/export': typeof AuthenticatedSettingsExportRoute
  '/_authenticated/submission/$submissionId': typeof AuthenticatedSubmissionSubmissionIdRoute
  '/api/public/og/$submissionId': typeof ApiPublicOgSubmissionIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/demo-review'
    | '/explore'
    | '/forgot-password'
    | '/health'
    | '/learn'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/billing'
    | '/dashboard'
    | '/practice'
    | '/review'
    | '/settings'
    | '/auth/callback'
    | '/blog/$slug'
    | '/explore/$slug'
    | '/learn/$slug'
    | '/s/$submissionId'
    | '/learn/'
    | '/admin/blog'
    | '/admin/curriculum'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/research'
    | '/admin/seats'
    | '/admin/settings'
    | '/admin/update-price'
    | '/settings/export'
    | '/submission/$submissionId'
    | '/api/public/og/$submissionId'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/demo-review'
    | '/explore'
    | '/forgot-password'
    | '/health'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/billing'
    | '/dashboard'
    | '/practice'
    | '/review'
    | '/settings'
    | '/auth/callback'
    | '/blog/$slug'
    | '/explore/$slug'
    | '/learn/$slug'
    | '/s/$submissionId'
    | '/learn'
    | '/admin/blog'
    | '/admin/curriculum'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/research'
    | '/admin/seats'
    | '/admin/settings'
    | '/admin/update-price'
    | '/settings/export'
    | '/submission/$submissionId'
    | '/api/public/og/$submissionId'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blog'
    | '/demo-review'
    | '/explore'
    | '/forgot-password'
    | '/health'
    | '/learn'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/practice'
    | '/_authenticated/review'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/blog/$slug'
    | '/explore/$slug'
    | '/learn/$slug'
    | '/s/$submissionId'
    | '/learn/'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/curriculum'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/export'
    | '/_authenticated/admin/research'
    | '/_authenticated/admin/seats'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/update-price'
    | '/_authenticated/settings/export'
    | '/_authenticated/submission/$submissionId'
    | '/api/public/og/$submissionId'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  DemoReviewRoute: typeof DemoReviewRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthRoute: typeof HealthRoute
  LearnRoute: typeof LearnRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SSubmissionIdRoute: typeof SSubmissionIdRoute
  ApiPublicOgSubmissionIdRoute: typeof ApiPublicOgSubmissionIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-review': {
      id: '/demo-review'
      path: '/demo-review'
      fullPath: '/demo-review'
      preLoaderRoute: typeof DemoReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/s/$submissionId': {
      id: '/s/$submissionId'
      path: '/s/$submissionId'
      fullPath: '/s/$submissionId'
      preLoaderRoute: typeof SSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/explore/$slug': {
      id: '/explore/$slug'
      path: '/$slug'
      fullPath: '/explore/$slug'
      preLoaderRoute: typeof ExploreSlugRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submission/$submissionId': {
      id: '/_authenticated/submission/$submissionId'
      path: '/submission/$submissionId'
      fullPath: '/submission/$submissionId'
      preLoaderRoute: typeof AuthenticatedSubmissionSubmissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/export': {
      id: '/_authenticated/settings/export'
      path: '/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof AuthenticatedSettingsExportRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/admin/update-price': {
      id: '/_authenticated/admin/update-price'
      path: '/admin/update-price'
      fullPath: '/admin/update-price'
      preLoaderRoute: typeof AuthenticatedAdminUpdatePriceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/seats': {
      id: '/_authenticated/admin/seats'
      path: '/admin/seats'
      fullPath: '/admin/seats'
      preLoaderRoute: typeof AuthenticatedAdminSeatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/research': {
      id: '/_authenticated/admin/research'
      path: '/admin/research'
      fullPath: '/admin/research'
      preLoaderRoute: typeof AuthenticatedAdminResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/export': {
      id: '/_authenticated/admin/export'
      path: '/admin/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AuthenticatedAdminExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/curriculum': {
      id: '/_authenticated/admin/curriculum'
      path: '/admin/curriculum'
      fullPath: '/admin/curriculum'
      preLoaderRoute: typeof AuthenticatedAdminCurriculumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/$submissionId': {
      id: '/api/public/og/$submissionId'
      path: '/api/public/og/$submissionId'
      fullPath: '/api/public/og/$submissionId'
      preLoaderRoute: typeof ApiPublicOgSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsExportRoute: typeof AuthenticatedSettingsExportRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsExportRoute: AuthenticatedSettingsExportRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminCurriculumRoute: typeof AuthenticatedAdminCurriculumRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminExportRoute: typeof AuthenticatedAdminExportRoute
  AuthenticatedAdminResearchRoute: typeof AuthenticatedAdminResearchRoute
  AuthenticatedAdminSeatsRoute: typeof AuthenticatedAdminSeatsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUpdatePriceRoute: typeof AuthenticatedAdminUpdatePriceRoute
  AuthenticatedSubmissionSubmissionIdRoute: typeof AuthenticatedSubmissionSubmissionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminCurriculumRoute: AuthenticatedAdminCurriculumRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminExportRoute: AuthenticatedAdminExportRoute,
  AuthenticatedAdminResearchRoute: AuthenticatedAdminResearchRoute,
  AuthenticatedAdminSeatsRoute: AuthenticatedAdminSeatsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUpdatePriceRoute: AuthenticatedAdminUpdatePriceRoute,
  AuthenticatedSubmissionSubmissionIdRoute:
    AuthenticatedSubmissionSubmissionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ExploreRouteChildren {
  ExploreSlugRoute: typeof ExploreSlugRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreSlugRoute: ExploreSlugRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  DemoReviewRoute: DemoReviewRoute,
  ExploreRoute: ExploreRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthRoute: HealthRoute,
  LearnRoute: LearnRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SSubmissionIdRoute: SSubmissionIdRoute,
  ApiPublicOgSubmissionIdRoute: ApiPublicOgSubmissionIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
