-- Add education content columns to topics table
ALTER TABLE public.topics
  ADD COLUMN IF NOT EXISTS overview TEXT,
  ADD COLUMN IF NOT EXISTS operations JSONB,
  ADD COLUMN IF NOT EXISTS common_patterns JSONB,
  ADD COLUMN IF NOT EXISTS when_to_use TEXT,
  ADD COLUMN IF NOT EXISTS when_to_avoid TEXT,
  ADD COLUMN IF NOT EXISTS maang_frequency TEXT,
  ADD COLUMN IF NOT EXISTS prerequisites JSONB;

-- Upsert education data for all 20 DSA topics
INSERT INTO public.topics (slug, name, category, description, overview, operations, common_patterns, when_to_use, when_to_avoid, maang_frequency, prerequisites)
VALUES
  ('arrays', 'Arrays', 'Data Structures',
   'Arrays store elements contiguously in memory, giving O(1) indexed access. Use for random access, fixed-size collections, and sequential data. Foundational to most DSA patterns.',
   'An array stores elements side-by-side in RAM, so accessing arr[i] takes constant time. This contiguous layout makes traversal fast but insertion and deletion slow; you must shift elements to make room or close gaps. Arrays underpin strings, hash tables, dynamic arrays (like Python lists), and most matrix/grid problems.',
   '[{"name": "Access by index", "time": "O(1)", "space": "O(1)"}, {"name": "Linear search", "time": "O(n)", "space": "O(1)"}, {"name": "Insert at end", "time": "O(1)*", "space": "O(1)"}, {"name": "Insert at position", "time": "O(n)", "space": "O(1)"}, {"name": "Delete at position", "time": "O(n)", "space": "O(1)"}, {"name": "Traverse", "time": "O(n)", "space": "O(1)"}]'::jsonb,
   '[{"name": "Two Pointers", "slug": "two-pointers"}, {"name": "Sliding Window", "slug": "sliding-window"}, {"name": "Binary Search", "slug": "binary-search"}, {"name": "Sorting", "slug": "sorting"}]'::jsonb,
   'Use arrays when you need fast indexed access, when the size is known up front, or when the problem involves sequential processing, subarrays, or range queries on static data.',
   'Avoid arrays when you need frequent insertions or deletions in the middle, dynamic resizing, or key-value lookups. Use linked lists, dynamic arrays, or hash maps instead.',
   'Very High',
   '[]'::jsonb),

  ('strings', 'Strings', 'Data Structures',
   'Strings are immutable character arrays with language-specific APIs. Master parsing, sliding windows, palindrome checks, and pattern matching for interview success.',
   'Strings are sequences of characters, essentially read-only arrays with a rich standard library. Immutability means every ''modification'' creates a new string, which has performance implications. String problems test your ability to manipulate character data, handle edge cases (empty strings, Unicode, case sensitivity), and apply array patterns (two-pointer, sliding window) to text.',
   '[{"name": "Access char", "time": "O(1)", "space": "O(1)"}, {"name": "Length", "time": "O(1)", "space": "O(1)"}, {"name": "Substring", "time": "O(k)", "space": "O(k)"}, {"name": "Concatenation", "time": "O(n+m)", "space": "O(n+m)"}, {"name": "Search (naive)", "time": "O(n*m)", "space": "O(1)"}, {"name": "Search (KMP)", "time": "O(n+m)", "space": "O(m)"}]'::jsonb,
   '[{"name": "Two Pointers", "slug": "two-pointers"}, {"name": "Sliding Window", "slug": "sliding-window"}, {"name": "Hash Maps", "slug": "hashing"}, {"name": "Recursion", "slug": "recursion"}]'::jsonb,
   'Use string-specific techniques for text processing, pattern matching, anagram detection, palindrome checks, and problems involving character frequency or ordering.',
   'Avoid treating strings as mutable arrays in languages where they are immutable (Java, Python, JS). Each concatenation in a loop is O(n^2); use StringBuilder/StringBuffer or join() instead.',
   'Very High',
   '["arrays"]'::jsonb),

  ('hashing', 'Hash Maps & Sets', 'Data Structures',
   'Hash maps and sets give O(1) average lookup, insert, and delete. A key optimization tool, converting O(n^2) pair-search into O(n).',
   'A hash map (dictionary, object, unordered_map) maps keys to values using a hash function. Keys are hashed to an array index; collisions are handled by chaining (linked lists) or open addressing. O(1) average-time operations make hashing one of the most common optimizations in interview problems. When you see ''find a pair,'' ''count frequencies,'' ''detect duplicates,'' or ''two-sum,'' consider a hash map first.',
   '[{"name": "Insert / put", "time": "O(1) avg", "space": "O(1)"}, {"name": "Lookup / get", "time": "O(1) avg", "space": "O(1)"}, {"name": "Delete / remove", "time": "O(1) avg", "space": "O(1)"}, {"name": "Contains / has", "time": "O(1) avg", "space": "O(1)"}, {"name": "Iterate keys/values", "time": "O(n)", "space": "O(1)"}]'::jsonb,
   '[{"name": "Two Pointers", "slug": "two-pointers"}, {"name": "Sliding Window", "slug": "sliding-window"}, {"name": "Arrays", "slug": "arrays"}, {"name": "Graphs", "slug": "graphs"}]'::jsonb,
   'Use hashing for frequency counting, duplicate detection, two-sum style pair-finding, memoization in DP, caching computed results, and adjacency list construction in graphs.',
   'Avoid when you need ordered traversal, range queries, or prefix/suffix operations. Use arrays (for integer keys with small range), trees, or balanced BSTs instead. Also avoid when worst-case O(n) collision time is unacceptable unless you''re confident in the hash function.',
   'Very High',
   '["arrays"]'::jsonb),

  ('linked-lists', 'Linked Lists', 'Data Structures',
   'Linked lists chain nodes via pointers. Master traversal, reversal, cycle detection, and in-place manipulation. Foundational for tree and graph problems.',
   'A linked list is a linear collection of nodes, each storing data and a pointer to the next node. Unlike arrays, linked lists don''t need contiguous memory, so insertion and deletion at known positions are O(1). The tradeoff is O(n) access by index and extra memory for pointers. Types: singly linked, doubly linked, and circular. Linked list problems test pointer manipulation, edge cases (empty list, single node), and the ability to track multiple references simultaneously.',
   '[{"name": "Access by index", "time": "O(n)", "space": "O(1)"}, {"name": "Insert at head", "time": "O(1)", "space": "O(1)"}, {"name": "Insert at position", "time": "O(n)", "space": "O(1)"}, {"name": "Delete at position", "time": "O(n)", "space": "O(1)"}, {"name": "Reverse (in-place)", "time": "O(n)", "space": "O(1)"}, {"name": "Detect cycle (Floyd)", "time": "O(n)", "space": "O(1)"}]'::jsonb,
   '[{"name": "Two Pointers", "slug": "two-pointers"}, {"name": "Recursion", "slug": "recursion"}, {"name": "Stacks", "slug": "stacks"}]'::jsonb,
   'Use linked lists when you need O(1) insertions/deletions at the head, for LRU cache implementations, when implementing stacks/queues, or when the problem explicitly requires pointer-based node manipulation.',
   'Avoid linked lists when you need random access by index, cache-friendly sequential access (arrays are faster), or when memory overhead per element matters.',
   'Medium',
   '["arrays"]'::jsonb),

  ('stacks', 'Stacks', 'Data Structures',
   'LIFO (Last In, First Out) structure. Use for backtracking, expression evaluation, monotonic stacks, and undo operations.',
   'A stack follows the Last In, First Out principle, like a stack of plates. The last element pushed is the first popped. Stacks are used for reversal, backtracking, bracket matching, and maintaining a ''recent history.'' The monotonic stack variant (maintaining sorted order) is an important pattern for next-greater-element and histogram problems.',
   '[{"name": "Push", "time": "O(1)", "space": "O(1)"}, {"name": "Pop", "time": "O(1)", "space": "O(1)"}, {"name": "Peek / Top", "time": "O(1)", "space": "O(1)"}, {"name": "Is Empty", "time": "O(1)", "space": "O(1)"}]'::jsonb,
   '[{"name": "Queues", "slug": "queues"}, {"name": "Recursion", "slug": "recursion"}, {"name": "Dynamic Programming", "slug": "dp"}]'::jsonb,
   'Use stacks for parenthesis matching, expression evaluation (infix to postfix), backtracking (DFS iterative), undo/redo, function call simulation, and monotonic stack problems (next greater/smaller element, largest rectangle in histogram).',
   'Avoid stacks when you need FIFO ordering (use a queue), random access by index, or when the depth is unknown and could overflow (use an explicit heap-allocated structure).',
   'High',
   '["arrays"]'::jsonb),

  ('queues', 'Queues', 'Data Structures',
   'FIFO (First In, First Out) structure. Powering BFS, sliding windows, task scheduling, and producer-consumer patterns.',
   'A queue follows the First In, First Out principle, like a line of people. Elements are added at the back and removed from the front. Queues drive Breadth-First Search (BFS), level-order tree traversal, and any problem involving ''processing in order of arrival.'' Variants include circular queues, dequeues (double-ended), and priority queues (heaps).',
   '[{"name": "Enqueue / Push", "time": "O(1)", "space": "O(1)"}, {"name": "Dequeue / Pop", "time": "O(1)", "space": "O(1)"}, {"name": "Peek / Front", "time": "O(1)", "space": "O(1)"}, {"name": "Is Empty", "time": "O(1)", "space": "O(1)"}]'::jsonb,
   '[{"name": "BFS / Graphs", "slug": "graphs"}, {"name": "Sliding Window", "slug": "sliding-window"}, {"name": "Stacks", "slug": "stacks"}]'::jsonb,
   'Use queues for BFS in trees and graphs, level-order traversal, processing tasks in arrival order, implementing caches (FIFO eviction), and sliding window maximum/minimum (dequeue).',
   'Avoid queues when you need LIFO ordering (use a stack), priority-based processing (use a heap), or random access by index.',
   'High',
   '["arrays", "linked-lists"]'::jsonb),

  ('recursion', 'Recursion', 'Paradigms',
   'A function calling itself. Master base cases, the call stack, and converting iterative thinking to recursive. Prerequisite for trees, graphs, DP, and backtracking.',
   'Recursion is a problem-solving technique where a function calls itself on smaller subproblems. Every recursive solution has two parts: a base case (when to stop) and a recursive case (how to reduce the problem). Understanding the call stack, that each recursive call creates a new stack frame, is key to avoiding stack overflow and tracing execution. Recursion is foundational for trees (naturally recursive), graphs (DFS), dynamic programming (top-down), and backtracking.',
   '[{"name": "Factorial / Fibonacci", "time": "O(2^n) naive", "space": "O(n) stack"}, {"name": "Tree DFS traversal", "time": "O(n)", "space": "O(h) stack"}, {"name": "Divide & conquer", "time": "O(n log n)", "space": "O(log n) stack"}]'::jsonb,
   '[{"name": "Trees", "slug": "trees"}, {"name": "Backtracking", "slug": "backtracking"}, {"name": "Dynamic Programming", "slug": "dp"}]'::jsonb,
   'Use recursion when a problem naturally decomposes into identical subproblems: tree traversal, divide and conquer (merge sort, quicksort), combinatorial enumeration (backtracking), or any depth-first graph exploration.',
   'Avoid recursion when the depth is unbounded (risk of stack overflow), when an iterative solution is equally clear and more efficient, or when tail-call optimization is not guaranteed by your language runtime.',
   'High',
   '[]'::jsonb),

  ('two-pointers', 'Two Pointers', 'Techniques',
   'Two indices traversing a sorted structure. Covers opposite-direction pairs, fast-slow pointer, and three-way partitioning in O(n) time.',
   'The two-pointer technique uses two indices (or references) moving through a data structure, often in opposite directions or at different speeds. It''s an effective technique for sorted arrays, palindrome checking, pair sums, and linked list cycle detection. By moving pointers strategically, you can often reduce O(n^2) pair-search to O(n).',
   '[{"name": "Opposite ends (sorted array pair sum)", "time": "O(n)", "space": "O(1)"}, {"name": "Fast & slow (cycle detection)", "time": "O(n)", "space": "O(1)"}, {"name": "Same direction (remove duplicates)", "time": "O(n)", "space": "O(1)"}, {"name": "Three-way partition (Dutch flag)", "time": "O(n)", "space": "O(1)"}]'::jsonb,
   '[{"name": "Arrays", "slug": "arrays"}, {"name": "Linked Lists", "slug": "linked-lists"}, {"name": "Strings", "slug": "strings"}]'::jsonb,
   'Use two pointers for sorted array pair/triplet problems, palindrome validation, in-place array manipulation, linked list cycle detection, and partitioning problems where a pivot splits elements into categories.',
   'Avoid when the data isn''t sorted and sorting would negate the optimization, or when the problem requires triple-nested search that can''t be reduced by pointer movement alone.',
   'Very High',
   '["arrays"]'::jsonb),

  ('sliding-window', 'Sliding Window', 'Techniques',
   'A fixed or variable window moving across arrays/strings. Optimizes substring, subarray, and K-sized window problems from O(n^2) to O(n).',
   'The sliding window technique maintains a range [left, right] that expands and contracts across a linear structure. Instead of recomputing from scratch for every subarray, you add the new right element and remove the left element as the window slides. Fixed-size windows are simpler (just slide); variable-size windows require condition-based expansion/contraction. This pattern appears in substring search, longest subarray with constraints, and any problem where a contiguous segment''s properties change incrementally.',
   '[{"name": "Fixed window (size K max sum)", "time": "O(n)", "space": "O(1)"}, {"name": "Variable window (longest without repeating chars)", "time": "O(n)", "space": "O(k)"}, {"name": "At-most K distinct (fruit into baskets)", "time": "O(n)", "space": "O(k)"}]'::jsonb,
   '[{"name": "Arrays", "slug": "arrays"}, {"name": "Strings", "slug": "strings"}, {"name": "Hash Maps", "slug": "hashing"}]'::jsonb,
   'Use sliding window for contiguous subarray/substring problems, maximum/minimum window size with constraints, problems involving distinct elements, character frequency, or any ''longest subarray with property X.''',
   'Avoid sliding window when the subarray constraint isn''t monotonic (expanding the window doesn''t guarantee the condition stays satisfied), or when the problem involves non-contiguous subsets.',
   'Very High',
   '["arrays", "strings", "hashing"]'::jsonb),

  ('binary-search', 'Binary Search', 'Algorithms',
   'Divide the search space in half each iteration. Applies to sorted arrays, monotonic functions, and answer-space search in O(log n) time.',
   'Binary search is not just for finding elements in a sorted array. The core idea, eliminating half the search space each step, applies to any problem with a monotonic predicate. Once you recognize that ''if condition X is true at position i, it''s true for all positions > i,'' you can binary search the boundary. This enables advanced applications: finding square roots, searching in rotated arrays, capacity planning (ship packages in D days), and minimax problems.',
   '[{"name": "Classic (sorted array search)", "time": "O(log n)", "space": "O(1)"}, {"name": "Lower bound / bisect_left", "time": "O(log n)", "space": "O(1)"}, {"name": "Rotated array search", "time": "O(log n)", "space": "O(1)"}, {"name": "Answer-space (allocate pages)", "time": "O(n log range)", "space": "O(1)"}]'::jsonb,
   '[{"name": "Arrays", "slug": "arrays"}, {"name": "Sorting", "slug": "sorting"}, {"name": "Greedy", "slug": "greedy"}]'::jsonb,
   'Use binary search on sorted arrays, when searching over a monotonic numeric range (capacity, speed, time), for finding the first/last occurrence, in rotated arrays, and whenever you can phrase a decision problem as ''can we do X with capacity Y?''.',
   'Avoid binary search on unsorted data, when the predicate is non-monotonic, or when O(n) linear scan is simpler and n is small enough that log n doesn''t matter.',
   'Very High',
   '["arrays"]'::jsonb),

  ('sorting', 'Sorting', 'Algorithms',
   'Arranging data to enable efficient algorithms. Know merge sort (divide & conquer), quicksort (partitioning), and when O(n log n) is the comparison-sort lower bound.',
   'Sorting is often a preprocessing step that enables two-pointer, binary search, and greedy solutions. Understanding the tradeoffs: merge sort is stable and O(n log n) guaranteed, quicksort is in-place but O(n^2) worst-case, heapsort gives O(n log n) in-place, helps you choose the right tool. Counting sort and radix sort break the O(n log n) comparison-sort barrier for integer keys with limited range.',
   '[{"name": "Merge Sort", "time": "O(n log n)", "space": "O(n)"}, {"name": "Quick Sort", "time": "O(n log n) avg", "space": "O(log n) stack"}, {"name": "Heap Sort", "time": "O(n log n)", "space": "O(1)"}, {"name": "Counting Sort (int keys)", "time": "O(n + k)", "space": "O(k)"}]'::jsonb,
   '[{"name": "Two Pointers", "slug": "two-pointers"}, {"name": "Binary Search", "slug": "binary-search"}, {"name": "Greedy", "slug": "greedy"}]'::jsonb,
   'Sort as preprocessing when it enables a greedy choice, two-pointer traversal, or binary search. Also use sorting for merge intervals, finding duplicates, and organizing data for efficient queries.',
   'Avoid sorting when O(n log n) is too slow and O(n) alternatives exist (hash map for duplicates, quickselect for k-th element). Also avoid if the original order carries semantic meaning you can''t recover.',
   'High',
   '["arrays"]'::jsonb),

  ('trees', 'Trees', 'Data Structures',
   'Hierarchical data with nodes and edges. Binary trees, N-ary trees, traversal (pre/in/post/level order), used widely for hierarchical problem modeling.',
   'A tree is a connected, acyclic graph, a hierarchical structure where each node has zero or more children and exactly one parent (except the root). Trees model hierarchies naturally: file systems, DOM, organization charts, decision trees. Binary trees (max 2 children) are a core interview topic. Traversal order: preorder (root-left-right), inorder (left-root-right), postorder (left-right-root), level-order (BFS), is the most tested concept, along with recursion on subtrees.',
   '[{"name": "DFS (pre/in/post order)", "time": "O(n)", "space": "O(h) stack"}, {"name": "BFS / Level-order", "time": "O(n)", "space": "O(w) queue"}, {"name": "Insert in BST", "time": "O(h)", "space": "O(1)"}, {"name": "Search in BST", "time": "O(h)", "space": "O(1)"}, {"name": "Height calculation", "time": "O(n)", "space": "O(h)"}]'::jsonb,
   '[{"name": "Recursion", "slug": "recursion"}, {"name": "Binary Search Trees", "slug": "bst"}, {"name": "Graphs", "slug": "graphs"}]'::jsonb,
   'Use trees for hierarchical data, binary tree problems (traversal, LCA, path sums), expression parsing (syntax trees), decision trees, and anytime the problem mentions ''parent-child'' or ''nested'' relationships.',
   'Avoid trees when the data has cycles (use graphs), when a flat structure (array/hash map) is sufficient, or when the tree can degenerate into a linked list (use a self-balancing BST or alternative).',
   'Very High',
   '["recursion", "queues"]'::jsonb),

  ('bst', 'Binary Search Trees', 'Data Structures',
   'Binary Search Tree: left < root < right. Gives O(log n) search/insert in balanced form. Underpins TreeMap, TreeSet, and database B-trees.',
   'A Binary Search Tree enforces the ordering property: for every node, left subtree values < node value < right subtree values. This gives O(h) search, insert, and delete where h is the tree height. In a balanced BST (AVL, Red-Black), h = O(log n), giving logarithmic operations. BSTs underpin ordered maps, sorted sets, and range queries, whenever you need ''next greater element'' or ''values in range [L, R]'' efficiently.',
   '[{"name": "Search", "time": "O(h)", "space": "O(1)"}, {"name": "Insert", "time": "O(h)", "space": "O(1)"}, {"name": "Delete", "time": "O(h)", "space": "O(1)"}, {"name": "Inorder (sorted output)", "time": "O(n)", "space": "O(h)"}, {"name": "Min / Max", "time": "O(h)", "space": "O(1)"}]'::jsonb,
   '[{"name": "Trees", "slug": "trees"}, {"name": "Recursion", "slug": "recursion"}, {"name": "Binary Search", "slug": "binary-search"}]'::jsonb,
   'Use BST when you need ordered operations (floor, ceiling, range queries) with better-than-O(n) performance, or when the problem involves validating or manipulating BST properties (inorder must be sorted).',
   'Avoid BST when you only need key-value lookups (use a hash map), when the tree can become skewed (use a self-balancing variant or alternative), or when O(n) preprocessing + O(1) queries via array is simpler.',
   'Medium',
   '["trees", "recursion"]'::jsonb),

  ('heaps', 'Heaps & Priority Queues', 'Data Structures',
   'Priority queues giving O(1) access to min/max element and O(log n) insertion. Essential for Top-K, Dijkstra, Huffman coding, and scheduling.',
   'A heap is a complete binary tree satisfying the heap property: in a min-heap, every parent is smaller than its children (root is global minimum). Heaps give O(1) access to the extremum and O(log n) insert/delete. They''re usually implemented as arrays for cache efficiency. Use cases: Top-K elements (maintain a K-sized heap), merging K sorted lists, Dijkstra''s shortest path, median maintenance (two heaps), and task scheduling.',
   '[{"name": "Peek (min/max)", "time": "O(1)", "space": "O(1)"}, {"name": "Push / Insert", "time": "O(log n)", "space": "O(1)"}, {"name": "Pop / Extract", "time": "O(log n)", "space": "O(1)"}, {"name": "Heapify (build)", "time": "O(n)", "space": "O(1)"}]'::jsonb,
   '[{"name": "Sorting", "slug": "sorting"}, {"name": "Graphs", "slug": "graphs"}, {"name": "Greedy", "slug": "greedy"}]'::jsonb,
   'Use heaps for Top-K problems, K-way merge, Dijkstra''s and Prim''s algorithms, median from data stream (two-heap pattern), task scheduling (CPU with cooldown), and whenever you need repeated access to the current minimum/maximum.',
   'Avoid heaps when you need full sorting (just sort the array), when you need ordered traversal of all elements, or when the problem requires searching for arbitrary elements (heaps don''t support efficient search).',
   'High',
   '["arrays", "trees"]'::jsonb),

  ('graphs', 'Graphs', 'Data Structures',
   'Nodes connected by edges. Model networks, relationships, and state spaces. BFS finds shortest paths; DFS explores connectivity and cycles.',
   'A graph G = (V, E) consists of vertices (nodes) connected by edges. Graphs model real-world networks: social graphs, road maps, web links, dependency trees. Representations: adjacency list (O(V+E) memory, good for sparse graphs) or adjacency matrix (O(V^2), good for dense). BFS finds shortest paths in unweighted graphs; DFS detects cycles, finds connected components, and enables topological sort. Weighted graph algorithms (Dijkstra, Bellman-Ford, Floyd-Warshall) are interview staples.',
   '[{"name": "BFS (shortest path, unweighted)", "time": "O(V + E)", "space": "O(V)"}, {"name": "DFS (cycle detection, topo sort)", "time": "O(V + E)", "space": "O(V)"}, {"name": "Dijkstra (weighted, non-negative)", "time": "O((V+E) log V)", "space": "O(V)"}, {"name": "Bellman-Ford (negative edges)", "time": "O(V * E)", "space": "O(V)"}, {"name": "Union-Find (DSU)", "time": "O(alpha(V))", "space": "O(V)"}]'::jsonb,
   '[{"name": "Queues", "slug": "queues"}, {"name": "Heaps", "slug": "heaps"}, {"name": "Dynamic Programming", "slug": "dp"}]'::jsonb,
   'Use graphs when the problem involves entities and their relationships, network flow, dependency ordering, state machines, grid traversal (BFS/DFS on 2D grid), or shortest/longest path problems.',
   'Avoid graph representations when the relationships can be modeled more simply (arrays, trees), when the graph is so dense that matrix representation would exceed memory, or when a non-graph algorithm (DP, greedy) solves it more efficiently.',
   'Very High',
   '["trees", "queues", "recursion"]'::jsonb),

  ('dp', 'Dynamic Programming', 'Paradigms',
   'Dynamic Programming, solve by breaking into overlapping subproblems. Master memoization (top-down) and tabulation (bottom-up) for optimization problems.',
   'Dynamic Programming is not a specific algorithm but a technique: solve a problem by combining solutions to overlapping subproblems, storing results to avoid recomputation. Two approaches: top-down (memoization, recursive with cache) and bottom-up (tabulation, iterative table filling). DP applies when a problem has optimal substructure (optimal solution built from optimal sub-solutions) and overlapping subproblems. Classic problems: knapsack, LCS, edit distance, coin change, matrix chain multiplication.',
   '[{"name": "1D DP (Fibonacci, climbing stairs)", "time": "O(n)", "space": "O(1) opt"}, {"name": "2D DP (LCS, edit distance)", "time": "O(n*m)", "space": "O(n*m) → O(min(n,m))"}, {"name": "Knapsack (0/1)", "time": "O(n*W)", "space": "O(W) opt"}, {"name": "Grid DP (unique paths, min path sum)", "time": "O(n*m)", "space": "O(m) opt"}]'::jsonb,
   '[{"name": "Recursion", "slug": "recursion"}, {"name": "Backtracking", "slug": "backtracking"}, {"name": "Greedy", "slug": "greedy"}]'::jsonb,
   'Use DP when the problem asks for ''minimum/maximum/count of ways,'' involves choices with constraints, has clearly defined states and transitions, and overlapping subproblems exist. If you find yourself solving the same subproblem multiple times in recursion, it''s DP territory.',
   'Avoid DP when subproblems don''t overlap (divide and conquer is sufficient), when the state space is too large for memoization, or when a greedy choice property lets you make optimal local decisions without exploring all options.',
   'Very High',
   '["recursion", "arrays"]'::jsonb),

  ('greedy', 'Greedy', 'Paradigms',
   'Make the locally optimal choice at each step. Works when the problem has optimal substructure and the greedy-choice property holds.',
   'A greedy algorithm builds a solution incrementally, always choosing the option that looks best at the moment, never reconsidering past choices. Greedy works when the problem exhibits the greedy-choice property: a locally optimal choice leads to a globally optimal solution. Classic examples: activity selection, Huffman coding, fractional knapsack, coin change (with canonical denominations), Kruskal''s and Prim''s for MST. The hard part is proving that greedy is correct; many problems look greedy but require DP.',
   '[{"name": "Activity selection", "time": "O(n log n)", "space": "O(1)"}, {"name": "Interval scheduling", "time": "O(n log n)", "space": "O(1)"}, {"name": "Huffman coding", "time": "O(n log n)", "space": "O(n)"}]'::jsonb,
   '[{"name": "Sorting", "slug": "sorting"}, {"name": "Heaps", "slug": "heaps"}, {"name": "Dynamic Programming", "slug": "dp"}]'::jsonb,
   'Use greedy when you can prove the greedy-choice property (often by contradiction or exchange argument), when the problem asks for minimum/maximum with a clear ordering, or when it''s a known greedy problem (interval scheduling, gas station, jump game).',
   'Avoid greedy when it fails for counterexamples; always test with small cases. If the greedy choice can lead to a dead end that requires backtracking, it''s likely a DP problem. When in doubt, code a DP solution and check if greedy matches on test cases.',
   'High',
   '["sorting", "arrays"]'::jsonb),

  ('backtracking', 'Backtracking', 'Paradigms',
   'Systematically explore all candidates, abandoning (''backtracking'') dead ends. The technique behind permutations, N-Queens, Sudoku, and combinatorial search.',
   'Backtracking is a systematic trial-and-error search. You build candidates incrementally and abandon a partial candidate (''backtrack'') as soon as you determine it cannot be completed to a valid solution. It''s essentially DFS through a state space tree with pruning. The template: choose → explore → un-choose. Backtracking generates all solutions (permutations, subsets, combinations) or finds one solution that satisfies constraints (N-Queens, Sudoku, word search).',
   '[{"name": "Generate all permutations", "time": "O(n!)", "space": "O(n)"}, {"name": "Generate all subsets", "time": "O(2^n)", "space": "O(n)"}, {"name": "N-Queens", "time": "O(n!)", "space": "O(n^2) board"}, {"name": "Sudoku solver", "time": "O(9^m)", "space": "O(1)"}]'::jsonb,
   '[{"name": "Recursion", "slug": "recursion"}, {"name": "Dynamic Programming", "slug": "dp"}, {"name": "Graphs", "slug": "graphs"}]'::jsonb,
   'Use backtracking for combinatorial enumeration (permutations, combinations, subsets), constraint satisfaction (N-Queens, Sudoku), path finding in mazes/grids with obstacles, and anytime you need to find all valid configurations exhaustively.',
   'Avoid backtracking when the state space is huge and un-prunable (use DP or math), when you only need one solution and a faster heuristic exists, or when the problem has optimal substructure (DP will be exponentially faster).',
   'Medium',
   '["recursion"]'::jsonb),

  ('bit-manipulation', 'Bit Manipulation', 'Techniques',
   'Operate directly on binary representations. XOR tricks, bit masks, and power-of-two checks, useful for compact representation and common in interviews.',
   'Bit manipulation uses binary representation to achieve O(1) operations that would otherwise take O(n) or O(log n). Core operations: AND (&), OR (|), XOR (^), NOT (~), left shift (<<), right shift (>>). XOR is particularly useful: x ^ x = 0, x ^ 0 = x, and XOR is commutative/associative, enabling single-number and swap tricks. Bit masks represent sets compactly (int can hold 32 boolean flags). Useful for subsets, permissions, and state compression in DP.',
   '[{"name": "Get i-th bit", "time": "O(1)", "space": "O(1)"}, {"name": "Set i-th bit", "time": "O(1)", "space": "O(1)"}, {"name": "Count set bits (popcount)", "time": "O(k) or O(1) builtin", "space": "O(1)"}, {"name": "Check power of two", "time": "O(1)", "space": "O(1)"}, {"name": "XOR tricks (single number)", "time": "O(n)", "space": "O(1)"}]'::jsonb,
   '[{"name": "Arrays", "slug": "arrays"}, {"name": "Dynamic Programming", "slug": "dp"}, {"name": "Hash Maps", "slug": "hashing"}]'::jsonb,
   'Use bit manipulation for space optimization (packing flags), XOR-based single-number detection, power-of-two checks, subset generation via bitmask (0 to 2^n), and any problem with constraints n <= 20 (hinting at 2^n bitmask DP).',
   'Avoid bit manipulation when clarity matters more than micro-optimizations; readable code using booleans or sets is preferred unless performance/space is critical. Also avoid when n > 64 (bitmask outgrows integer size).',
   'Medium',
   '[]'::jsonb),

  ('complexity', 'Time & Space Complexity', 'Concepts',
   'Big-O analysis of time and space. A fundamental interview evaluation criterion: understand logarithmic, linearithmic, and exponential growth.',
   'Time and space complexity analysis is how we measure algorithm efficiency independent of hardware. Big-O notation describes the upper bound of growth rate as input size n approaches infinity. Common classes: O(1) constant, O(log n) logarithmic, O(n) linear, O(n log n) linearithmic, O(n^2) quadratic, O(2^n) exponential. Mastering complexity analysis means you can predict which solution will pass interview constraints (n=10^6 needs O(n) or O(n log n); n=20 allows O(2^n)).',
   '[{"name": "O(1), constant", "time": "Instant regardless of n", "space": "Constant"}, {"name": "O(log n), logarithmic", "time": "Binary search, balanced trees", "space": "Recursion depth"}, {"name": "O(n), linear", "time": "Single pass, two-pointer", "space": "Input copy"}, {"name": "O(n log n), linearithmic", "time": "Sorting, divide & conquer", "space": "Merge sort memory"}, {"name": "O(n^2), quadratic", "time": "Nested loops, pair-search", "space": "DP table"}, {"name": "O(2^n), exponential", "time": "Brute-force subsets", "space": "Recursion tree"}]'::jsonb,
   '[{"name": "Sorting", "slug": "sorting"}, {"name": "Binary Search", "slug": "binary-search"}, {"name": "Dynamic Programming", "slug": "dp"}]'::jsonb,
   'Analyze complexity for every solution. Before coding, check constraints: if n <= 10^5 and your algorithm is O(n^2), it will TLE (time limit exceeded). Use complexity analysis to choose the right algorithm before you start writing code.',
   'Don''t obsess over complexity when n is trivially small. Don''t sacrifice code clarity for minor constant-factor gains unless profiling proves it matters. Big-O ignores constants; an O(n) algorithm with large constants can be slower than O(n^2) for small n.',
   'Very High',
   '[]'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  description = EXCLUDED.description,
  overview = EXCLUDED.overview,
  operations = EXCLUDED.operations,
  common_patterns = EXCLUDED.common_patterns,
  when_to_use = EXCLUDED.when_to_use,
  when_to_avoid = EXCLUDED.when_to_avoid,
  maang_frequency = EXCLUDED.maang_frequency,
  prerequisites = EXCLUDED.prerequisites;
