ALTER TABLE progress ADD COLUMN IF NOT EXISTS stability DOUBLE PRECISION DEFAULT 2.5;
ALTER TABLE progress ADD COLUMN IF NOT EXISTS difficulty DOUBLE PRECISION DEFAULT 5.0;
ALTER TABLE progress ADD COLUMN IF NOT EXISTS retrievability DOUBLE PRECISION DEFAULT 0.9;
ALTER TABLE progress ADD COLUMN IF NOT EXISTS next_review_date TIMESTAMPTZ;
